LineLength:
  Max: 200

HashSyntax:
  EnforcedStyle: hash_rockets

SingleSpaceBeforeFirstArg:
  Exclude:
    - "**/metadata.rb"

AllCops:
  Exclude:
    - "Vagrantfile"
    - "Thorfile"
    - "Guardfile"
    - "Berksfile"
    - ".kitchen/**/*"
    - "providers/**/*"
